baseURL = 'https://rbd0.github.io/blog/'
languageCode = 'en-us'
title = 'Rahul Dintyala'
theme = 'hugo-theme-tokiwa'

[social]
bilibili = "http://example.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "http://example.com/"
mail = "mailto:anon@example.com"
twitter = "https://twitter.com/"
weibo = "http://example.com/"
youtube = "https://youtube.com/"
zhihu = "http://example.com/"